// @flow

// ERROR
export const ERROR = 'RNRX/ERROR';
export const CLEAR_ERROR = 'RNRX/ERROR/CLEAR';

// ROUTER
export const SWITCH_ROUTE = 'RNRX/ROUTER/SWITCH';

// APPS
export const OPEN_APP = 'RNRX/APPS/OPEN';
export const SELECT_APP = 'RNRX/APPS/SELECT';
export const CLOSE_APP = 'RNRX/APPS/CLOSE';
export const APP_HAS_PACKAGE = 'RNRX/APPS/HAS_PACKAGE';

// METRO
export const START_METRO = 'RNRX/METRO/START';
export const METRO_DOWN = 'RNRX/METRO/DOWN';
export const METRO_OUTPUT = 'RNRX/METRO/OUTPUT';
export const METRO_PID = 'RNRX/METRO/PID';
export const CHANGE_METRO_PORT = 'RNRX/METRO/CHANGE_PORT';

// INIT
export const INIT_OUTPUT = 'RNRX/INIT/OUTPUT';

// INFO
export const GET_INFO = 'RNRX/INFO/GET';
export const GOT_INFO = 'RNRX/INFO/GOT';
export const FAILED_GETTING_INFO = 'RNRX/INFO/FAILED';

// RUN ANDROID
export const RUN_ANDROID = 'RNRX/ANDROID/RUN/RUNNING';
export const FAILED_RUNNING_ANDROID = 'RNRX/ANDROID/RUN/FAILED';
export const STOP_ANDROID = 'RNRX/ANDROID/STOP/STOPPING';
export const FAILED_STOPPING_ANDROID = 'RNRX/ANDROID/STOP/FAILED';

// RUN IOS
export const RUN_IOS = 'RNRX/IOS/RUN/RUNNING';
export const FAILED_RUNNING_IOS = 'RNRX/IOS/RUN/FAILED';
export const STOP_IOS = 'RNRX/IOS/STOP/STOPPING';
export const FAILED_STOPPING_IOS = 'RNRX/IOS/STOP/FAILED';
