// @flow

// ERROR
export const ERROR = 'RNRX/ERROR';
export const CLEAR_ERROR = 'RNRX/ERROR/CLEAR';

// ROUTER
export const SWITCH_ROUTE = 'RNRX/ROUTER/SWITCH';

// APP ROUTER
export const SWITCH_APP_ROUTE = 'RNRX/ROUTER/APP/SWITCH';

// PLATFORM ROUTER
export const SWITCH_PLATFORM_ROUTE = 'RNRX/ROUTER/PLATFORM/SWITCH';

// APPS
export const OPEN_APP = 'RNRX/APPS/OPEN';
export const CLOSE_APP = 'RNRX/APPS/CLOSE';
export const VIEW_APP = 'RNRX/APPS/VIEW';
export const HIDE_APP = 'RNRX/APPS/HIDE';

// INFO
export const GOT_INFO = 'RNRX/INFO/GOT';
export const FAILED_GETTING_INFO = 'RNRX/INFO/FAILED';

// APK
export const FAILED_GETTING_APK = 'RNRX/ANDROID/APK/GET/FAILED';
export const FAILED_GENERATING_APK = 'RNRX/ANDROID/APK/GEN/FAILED';
